print("The love calculator is calculating your love score...")
name1 = input("What is your name? \n")
name2 = input("What is their name? \n")
combined_names = name1.lower() + name2.lower()
t = combined_names.count("t")
r = combined_names.count("r")
u = combined_names.count("u")       
e = combined_names.count("e")
true = t + r + u + e
l = combined_names.count("l")
o = combined_names.count("o")                                       
v = combined_names.count("v")
e = combined_names.count("e")
love = l + o + v + e
love_score = int(str(true) + str(love))
print(f"Your love score is {love_score}")